services:
  docs:
    image: ccs_docker_local_docs
    container_name: ccs_docker_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ccs_docker:/app/ccs_docker:z
    ports:
      - '9000:9000'
    command: /start-docs
