# Generated by Django 4.1.8 on 2023-04-07 12:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArrestAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50, null=True)),
                ("guardian_name", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=50, null=True)),
                ("user_id", models.IntegerField()),
                ("crime_id", models.IntegerField(null=True)),
                ("stop_alerting", models.BooleanField(null=True)),
                ("matched", models.BooleanField(null=True)),
                ("match_details", models.CharField(max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BufferImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("avatar_url", models.FileField(upload_to="")),
                ("criminal_id", models.UUIDField(null=True)),
                ("icon", models.BooleanField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CrimeNewsSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("cns", models.FileField(upload_to="")),
                ("cns_date", models.DateField()),
                ("processed", models.BooleanField(null=True)),
                ("casesuploaded", models.IntegerField(blank=True, null=True)),
                (
                    "crime_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=20),
                        null=True,
                        size=None,
                    ),
                ),
                ("csv", models.FileField(blank=True, null=True, upload_to="")),
                ("rejected", models.CharField(blank=True, max_length=200)),
                ("existing", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CriminalDuplicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("reported_dup", models.CharField(max_length=200, null=True)),
                ("confirmed_dup", models.CharField(max_length=200, null=True)),
                ("user_id", models.IntegerField()),
                ("processsed", models.BooleanField(null=True)),
                ("selected_name", models.IntegerField(null=True)),
                ("selected_dob", models.IntegerField(null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Merge_Selected_records"),
                            (1, "Not_Duplicate"),
                            (2, "Doubtful_But_Possible"),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyArrest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("da_date", models.DateField()),
                ("cns", models.FileField(upload_to="")),
                ("processed", models.BooleanField(null=True)),
                ("criminals_added", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MergeTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=200, null=True)),
                ("second", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
