# Generated by Django 4.1.8 on 2023-04-16 11:56

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_create_vector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceEncoding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=36)),
                ("embedding", pgvector.django.VectorField(dimensions=128)),
            ],
        ),
    ]
