# Generated by Django 4.1.8 on 2023-04-17 09:42

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_faceencoding"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="faceencoding",
            index=pgvector.django.IvfflatIndex(
                fields=["embedding"],
                lists=100,
                name="my_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
