# Generated by Django 4.1.8 on 2023-04-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvancedCrimeSearchChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("keywords", models.CharField(max_length=100, null=True)),
                ("full_text_search_type", models.IntegerField(null=True)),
                ("tags", models.CharField(max_length=100, null=True)),
                ("search_any_tags", models.BooleanField(null=True)),
                ("ps_list", models.CharField(max_length=500, null=True)),
                ("districts", models.CharField(max_length=200, null=True)),
                ("min_date", models.CharField(max_length=10, null=True)),
                ("max_date", models.CharField(max_length=10, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdvancedCriminalSearchChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("keywords", models.CharField(max_length=100, null=True)),
                ("full_text_search_type", models.IntegerField(null=True)),
                ("tags", models.CharField(max_length=100, null=True)),
                ("search_any_tags", models.BooleanField(null=True)),
                ("ps_list", models.CharField(max_length=500, null=True)),
                ("districts", models.CharField(max_length=200, null=True)),
                ("min_date", models.CharField(max_length=10, null=True)),
                ("max_date", models.CharField(max_length=10, null=True)),
                ("first_name", models.CharField(max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50, null=True)),
                ("guardian_first_name", models.CharField(max_length=50, null=True)),
                ("aliases", models.CharField(max_length=50, null=True)),
                ("exact_name_search", models.BooleanField(null=True)),
                ("address", models.CharField(max_length=50, null=True)),
                ("id_mark", models.CharField(max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
