#!/bin/bash

set -o errexit
set -o nounset

# Wait for the database to be ready
python /app/manage.py wait_for_db

exec watchfiles --filter python celery.__main__.main --args '-A config.celery_app worker -l INFO'
